cmake_minimum_required(VERSION 4.2)
project(sample_qwidget)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_AUTOMOC ON)
set(CMAKE_AUTORCC ON)
set(CMAKE_AUTOUIC ON)

find_package(Qt6 COMPONENTS
        Core
        Gui
        Widgets
        REQUIRED)

add_executable(sample_qwidget main.cpp
        mainwindow.cpp mainwindow.h
        mainwindow.cpp
        mainwindow.h
        mainwindow.ui)

target_link_libraries(sample_qwidget
        Qt::Core
        Qt::Gui
        Qt::Widgets
)

